In [47]:
from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd

Game data from past 7 days (10/20 - 10/26)

In [50]:
data = leaguedashplayerstats.LeagueDashPlayerStats(season='2025-26')
players = data.get_data_frames()[0]
players.info
players.columns #player data

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK',
       'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK',
       'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK',
       'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK',
       'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK',
       'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT'],
      dtype='object')

In [51]:
players

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,1631260,AJ Green,AJ,1610612749,MIL,26.0,4,3,1,0.750,...,1,340,176,135,39,215,70,3,176,1
1,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,2,0,2,0.000,...,1,45,350,392,204,393,70,3,394,1
2,203932,Aaron Gordon,Aaron,1610612743,DEN,30.0,4,3,1,0.750,...,171,174,63,44,23,86,70,3,71,1
3,1628988,Aaron Holiday,Aaron,1610612745,HOU,29.0,1,1,0,1.000,...,1,1,350,336,194,382,70,3,371,1
4,1630174,Aaron Nesmith,Aaron,1610612754,IND,26.0,4,0,4,0.000,...,364,299,104,152,298,186,70,3,168,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,1642258,Zaccharie Risacher,Zaccharie,1610612737,ATL,20.0,3,1,2,0.333,...,171,116,273,229,233,272,70,3,267,1
417,203897,Zach LaVine,Zach,1610612758,SAC,30.0,5,1,4,0.200,...,319,248,45,4,410,29,70,3,22,1
418,1630192,Zeke Nnaji,Zeke,1610612743,DEN,24.0,3,3,0,1.000,...,1,116,273,327,265,364,70,3,362,1
419,1630533,Ziaire Williams,Ziaire,1610612751,BKN,24.0,3,0,3,0.000,...,171,273,220,203,265,250,70,3,236,1
420,1629627,Zion Williamson,Zion,1610612740,NOP,25.0,3,0,3,0.000,...,421,174,36,89,256,89,33,3,99,1

In [52]:
from nba_api.stats.endpoints import leaguedashteamstats
DATE_FROM = "2025-10-01"   
DATE_TO   = "2025-10-27"   

resp = leaguedashteamstats.LeagueDashTeamStats(
    season='2025-26',
    season_type_all_star='Regular Season',   # or 'Pre Season' if you want preseason
    date_from_nullable=DATE_FROM,
    date_to_nullable=DATE_TO,
    per_mode_detailed='PerGame'              # 'Totals' if you want raw sums
)

teams = resp.get_data_frames()[0]
teams # team data

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,4,1,3,0.250,48.0,40.8,89.5,0.455,...,28,10,4,22,17,5,4,15,25,24
1,1610612738,Boston Celtics,4,1,3,0.250,48.0,40.5,90.5,0.448,...,17,30,2,17,3,2,25,28,26,14
2,1610612751,Brooklyn Nets,4,0,4,0.000,48.0,40.8,89.3,0.457,...,29,17,14,25,30,18,28,23,21,30
3,1610612766,Charlotte Hornets,3,2,1,0.667,48.0,46.0,90.3,0.509,...,8,1,13,24,18,10,9,2,1,2
4,1610612741,Chicago Bulls,3,3,0,1.000,48.0,42.0,87.3,0.481,...,8,5,29,20,15,25,14,16,16,8
5,1610612739,Cleveland Cavaliers,4,3,1,0.750,48.0,40.5,85.0,0.476,...,25,15,20,3,19,5,12,4,14,9
6,1610612742,Dallas Mavericks,4,1,3,0.250,48.0,38.0,85.8,0.443,...,18,22,16,14,13,17,3,10,30,26
7,1610612743,Denver Nuggets,3,2,1,0.667,49.7,46.7,89.0,0.524,...,14,6,7,11,27,25,14,21,2,4
8,1610612765,Detroit Pistons,4,2,2,0.500,48.0,39.3,91.8,0.428,...,7,21,23,17,1,27,29,11,28,21
9,1610612744,Golden State Warriors,4,3,1,0.750,49.3,41.8,85.0,0.491,...,24,3,20,6,19,5,8,17,4,16
10,1610612745,Houston Rockets,3,1,2,0.333,51.3,41.3,88.3,0.468,...,12,23,15,6,21,18,20,1,6,7
11,1610612754,Indiana Pacers,3,0,3,0.000,51.3,40.3,95.0,0.425,...,6,24,8,30,15,3,30,5,20,27
12,1610612746,LA Clippers,3,2,1,0.667,48.0,42.7,81.3,0.525,...,16,7,30,4,5,10,9,21,17,13
13,1610612747,Los Angeles Lakers,4,2,2,0.500,48.0,41.5,79.8,0.520,...,22,19,28,17,25,18,1,13,15,17
14,1610612763,Memphis Grizzlies,4,2,2,0.500,48.0,40.8,90.0,0.453,...,20,9,5,27,8,13,11,9,9,19
15,1610612748,Miami Heat,3,2,1,0.667,48.0,45.7,92.0,0.496,...,2,8,27,4,27,15,14,26,3,3
16,1610612749,Milwaukee Bucks,3,2,1,0.667,48.0,45.7,89.0,0.513,...,13,10,10,10,10,3,20,26,8,12
17,1610612750,Minnesota Timberwolves,4,2,2,0.500,48.0,40.5,85.8,0.472,...,22,27,10,22,3,9,23,23,22,22
18,1610612740,New Orleans Pelicans,3,0,3,0.000,49.7,38.3,93.0,0.412,...,19,29,8,11,29,30,18,2,29,29
19,1610612752,New York Knicks,3,2,1,0.667,48.0,36.0,90.0,0.400,...,3,25,18,20,21,10,5,23,27,15
20,1610612760,Oklahoma City Thunder,4,4,0,1.000,53.0,43.5,95.5,0.455,...,4,26,3,11,24,13,23,8,11,6
21,1610612753,Orlando Magic,4,1,3,0.250,48.0,39.5,84.3,0.469,...,11,27,23,27,11,18,17,6,24,23
22,1610612755,Philadelphia 76ers,3,3,0,1.000,48.0,42.7,89.7,0.476,...,26,14,1,29,6,15,22,7,5,11
23,1610612756,Phoenix Suns,4,1,3,0.250,49.3,41.3,94.8,0.435,...,15,12,19,8,8,18,27,17,18,28
24,1610612757,Portland Trail Blazers,4,2,2,0.500,48.0,41.8,94.5,0.442,...,20,13,23,1,13,29,2,13,13,10
25,1610612758,Sacramento Kings,3,1,2,0.333,48.0,44.0,92.7,0.475,...,30,18,5,2,6,8,7,29,23,18
26,1610612759,San Antonio Spurs,4,4,0,1.000,49.3,43.3,82.5,0.524,...,5,19,23,14,2,1,12,11,11,1
27,1610612761,Toronto Raptors,4,1,3,0.250,48.0,45.5,89.8,0.507,...,27,2,16,8,25,24,25,17,10,19
28,1610612762,Utah Jazz,3,2,1,0.667,49.7,43.3,93.7,0.463,...,1,4,22,16,21,28,5,20,7,5
29,1610612764,Washington Wizards,3,1,2,0.333,48.0,42.7,93.0,0.459,...,10,16,10,26,12,18,18,30,19,25

In [53]:
from nba_api.stats.endpoints import leaguegamelog

gamelog = leaguegamelog.LeagueGameLog(
    season='2025-26',
    season_type_all_star='Regular Season'
)
#game data
games = gamelog.get_data_frames()[0]

In [54]:
games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'] )

In [55]:
games = games[(games['GAME_DATE'] >= '2025-10-20') & (games['GAME_DATE'] <= '2025-10-26')]
games['GAME_DATE']

0    2025-10-21
1    2025-10-21
2    2025-10-21
3    2025-10-21
4    2025-10-22
        ...
79   2025-10-26
80   2025-10-26
81   2025-10-26
82   2025-10-26
83   2025-10-26
Name: GAME_DATE, Length: 84, dtype: datetime64[ns]

In [56]:
#get data of how the game progressed over time...quarter by quarter stats?
from nba_api.stats.endpoints import playbyplayv2
from time import sleep

game_ids = games["GAME_ID"].astype(str).unique()
all_pbp = []
for gid in game_ids:
    try:
        pbp = playbyplayv2.PlayByPlayV2(game_id=gid)
        df = pbp.get_data_frames()[0]
        df["GAME_ID"] = gid  # keep game id for reference
        all_pbp.append(df)
        sleep(0.6)  
    except Exception as e:
        print(f"Failed {gid}: {e}")

pbp_df = pd.concat(all_pbp, ignore_index=True) if all_pbp else pd.DataFrame()
pbp_df

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0022500001,2,12,0,1,7:44 PM,12:00,None,Start of 1st Period (7:44 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1
1,0022500001,4,10,0,1,7:44 PM,12:00,Jump Ball Holmgren vs. Adams: Tip to Thompson,None,None,...,Rockets,HOU,5,1641708,Amen Thompson,1.610613e+09,Houston,Rockets,HOU,1
2,0022500001,8,2,1,1,7:44 PM,11:36,None,None,MISS Sengun 25' 3PT Jump Shot,...,None,None,0,0,None,NaN,None,None,None,1
3,0022500001,9,4,0,1,7:44 PM,11:31,Wallace REBOUND (Off:0 Def:1),None,None,...,None,None,0,0,None,NaN,None,None,None,1
4,0022500001,10,1,98,1,7:45 PM,11:26,Holmgren 1' Cutting Layup Shot (2 PTS) (Dort 1...,None,None,...,Thunder,OKC,0,0,None,NaN,None,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21442,0022500105,702,4,0,4,4:44 PM,0:27,SPURS Rebound,None,None,...,None,None,0,0,None,NaN,None,None,None,1
21443,0022500105,704,5,11,4,4:44 PM,0:03,SPURS Turnover: Shot Clock (T#15),None,None,...,None,None,1,0,None,NaN,None,None,None,1
21444,0022500105,705,6,11,4,4:44 PM,0:03,None,Jordi Fernandez Foul:T.FOUL (T.Ford),None,...,None,None,1,0,None,NaN,None,None,None,1
21445,0022500105,706,3,16,4,4:45 PM,0:03,Wembanyama Free Throw Technical (31 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,1
21446,0022500105,707,13,0,4,4:45 PM,0:00,None,End of 4th Period (4:45 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1

 all the above data can go into a postgres database, its pretty much the whole base info for the week

In [57]:
games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,290,43,...,36,52,23,6,5,25,26,124,-1,1
1,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,240,38,...,31,40,29,10,4,19,27,119,10,1
2,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,240,42,...,32,39,23,7,2,20,21,109,-10,1
3,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,290,46,...,27,38,29,12,4,12,27,125,1,1
4,22025,1610612737,ATL,Atlanta Hawks,0022500082,2025-10-22,ATL vs. TOR,L,240,38,...,26,34,25,7,6,16,24,118,-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,22025,1610612749,MIL,Milwaukee Bucks,0022500107,2025-10-26,MIL @ CLE,L,240,40,...,28,37,25,12,6,18,26,113,-5,1
80,22025,1610612764,WAS,Washington Wizards,0022500109,2025-10-26,WAS vs. CHA,L,240,41,...,33,40,25,5,4,15,27,113,-26,1
81,22025,1610612751,BKN,Brooklyn Nets,0022500105,2025-10-26,BKN @ SAS,L,240,34,...,23,34,22,9,0,12,30,107,-11,1
82,22025,1610612759,SAS,San Antonio Spurs,0022500105,2025-10-26,SAS vs. BKN,W,240,39,...,34,45,20,7,6,15,23,118,11,1
83,22025,1610612766,CHA,Charlotte Hornets,0022500109,2025-10-26,CHA @ WAS,W,240,47,...,41,52,30,12,4,12,16,139,26,1

In [58]:
#all the games and their scores displayed neatly

#parse through the game data, given each game id
#show the home team, the away team, and the final score 

    #parse the 'matchup'  ..home team -> @ , away team -> vs 

games_unique = games.drop_duplicates(subset=['GAME_ID'])
games_unique
game_report = pd.DataFrame()

In [59]:
import numpy as np

# Create game_report from games_unique
game_report = games_unique[['GAME_ID', 'MATCHUP']].copy()

# Parse home and away teams from MATCHUP
# Format: "LAL vs. BOS" = LAL is home, "LAL @ BOS" = BOS is home
is_home_game = game_report['MATCHUP'].str.contains(' vs. ')
teams = game_report['MATCHUP'].str.split(r' vs. | @ ', regex=True, expand=True)

game_report['Home'] = np.where(is_home_game, teams[0], teams[1])
game_report['Away'] = np.where(is_home_game, teams[1], teams[0])
game_report['Matchup'] = game_report['MATCHUP']

# Get final scores by grouping games DataFrame (has both teams' scores)
scores = games.groupby('GAME_ID').agg({
    'TEAM_ABBREVIATION': list,
    'PTS': list
}).reset_index()

# Merge scores with game_report to get final scores
def get_scores(row):
    game_id = row['GAME_ID']
    score_data = scores[scores['GAME_ID'] == game_id]
    if len(score_data) == 0:
        return np.nan, np.nan
    
    teams_list = score_data.iloc[0]['TEAM_ABBREVIATION']
    pts_list = score_data.iloc[0]['PTS']
    
    # Find which score belongs to home and which to away
    home_idx = teams_list.index(row['Home']) if row['Home'] in teams_list else None
    away_idx = teams_list.index(row['Away']) if row['Away'] in teams_list else None
    
    if home_idx is not None and away_idx is not None:
        return pts_list[home_idx], pts_list[away_idx]
    return np.nan, np.nan

game_report[['Home_Score', 'Away_Score']] = game_report.apply(
    lambda row: pd.Series(get_scores(row)), axis=1
)


game_report['Final_Score'] = game_report.apply(
    lambda row: f"{row['Away']} @ {row['Home']}: {int(row['Away_Score'])} - {int(row['Home_Score'])}",
    axis=1
)

# Select and reorder columns
game_report = game_report[['GAME_ID', 'Matchup', 'Home', 'Away', 'Home_Score', 'Away_Score', 'Final_Score']]

# Ensure unique games only (drop duplicates by GAME_ID)
game_report = game_report.drop_duplicates(subset=['GAME_ID'], keep='first')
game_report

,GAME_ID,Matchup,Home,Away,Home_Score,Away_Score,Final_Score
0,0022500001,HOU @ OKC,OKC,HOU,125,124,HOU @ OKC: 124 - 125
1,0022500002,GSW @ LAL,LAL,GSW,109,119,GSW @ LAL: 119 - 109
4,0022500082,ATL vs. TOR,ATL,TOR,118,138,TOR @ ATL: 138 - 118
5,0022500081,MIA @ ORL,ORL,MIA,125,121,MIA @ ORL: 121 - 125
6,0022500080,BKN @ CHA,CHA,BKN,136,117,BKN @ CHA: 117 - 136
7,0022500003,NYK vs. CLE,NYK,CLE,119,111,CLE @ NYK: 111 - 119
9,0022500086,WAS @ MIL,MIL,WAS,133,120,WAS @ MIL: 120 - 133
11,0022500084,CHI vs. DET,CHI,DET,115,111,DET @ CHI: 111 - 115
14,0022500085,NOP @ MEM,MEM,NOP,128,122,NOP @ MEM: 122 - 128
18,0022500089,MIN @ POR,POR,MIN,114,118,MIN @ POR: 118 - 114
19,0022500087,UTA vs. LAC,UTA,LAC,129,108,LAC @ UTA: 108 - 129
22,0022500088,SAC @ PHX,PHX,SAC,120,116,SAC @ PHX: 116 - 120
23,0022500004,DAL vs. SAS,DAL,SAS,92,125,SAS @ DAL: 125 - 92
26,0022500083,BOS vs. PHI,BOS,PHI,116,117,PHI @ BOS: 117 - 116
28,0022500005,IND vs. OKC,IND,OKC,135,141,OKC @ IND: 141 - 135
30,0022500006,DEN @ GSW,GSW,DEN,137,131,DEN @ GSW: 131 - 137
32,0022500018,BOS @ NYK,NYK,BOS,105,95,BOS @ NYK: 95 - 105
33,0022500094,MEM vs. MIA,MEM,MIA,114,146,MIA @ MEM: 146 - 114
34,0022500093,DET @ HOU,HOU,DET,111,115,DET @ HOU: 115 - 111
35,0022500096,DAL vs. WAS,DAL,WAS,107,117,WAS @ DAL: 117 - 107
36,0022500091,CLE @ BKN,BKN,CLE,124,131,CLE @ BKN: 131 - 124
38,0022500019,MIN @ LAL,LAL,MIN,128,110,MIN @ LAL: 110 - 128
39,0022500097,GSW @ POR,POR,GSW,139,119,GSW @ POR: 119 - 139
41,0022500090,ATL @ ORL,ORL,ATL,107,111,ATL @ ORL: 111 - 107
45,0022500099,PHX @ LAC,LAC,PHX,129,102,PHX @ LAC: 102 - 129
46,0022500095,NOP vs. SAS,NOP,SAS,116,120,SAS @ NOP: 120 - 116
49,0022500098,SAC vs. UTA,SAC,UTA,105,104,UTA @ SAC: 104 - 105
51,0022500092,MIL @ TOR,TOR,MIL,116,122,MIL @ TOR: 122 - 116
56,0022500100,CHI @ ORL,ORL,CHI,98,110,CHI @ ORL: 110 - 98
57,0022500103,MEM vs. IND,MEM,IND,128,103,IND @ MEM: 103 - 128
60,0022500101,OKC @ ATL,ATL,OKC,100,117,OKC @ ATL: 117 - 100
61,0022500104,PHX @ DEN,DEN,PHX,133,111,PHX @ DEN: 111 - 133
64,0022500102,CHA @ PHI,PHI,CHA,125,121,CHA @ PHI: 121 - 125
66,0022500107,CLE vs. MIL,CLE,MIL,118,113,MIL @ CLE: 113 - 118
67,0022500110,IND @ MIN,MIN,IND,114,110,IND @ MIN: 110 - 114
68,0022500111,TOR @ DAL,DAL,TOR,139,129,TOR @ DAL: 129 - 139
69,0022500108,NYK @ MIA,MIA,NYK,115,107,NYK @ MIA: 107 - 115
72,0022500106,DET vs. BOS,DET,BOS,119,113,BOS @ DET: 113 - 119
74,0022500113,SAC vs. LAL,SAC,LAL,120,127,LAL @ SAC: 127 - 120
76,0022500112,LAC vs. POR,LAC,POR,114,107,POR @ LAC: 107 - 114
80,0022500109,WAS vs. CHA,WAS,CHA,113,139,CHA @ WAS: 139 - 113
81,0022500105,BKN @ SAS,SAS,BKN,118,107,BKN @ SAS: 107 - 118

In [60]:
game_report.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 0 to 81
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GAME_ID      42 non-null     object
 1   Matchup      42 non-null     object
 2   Home         42 non-null     object
 3   Away         42 non-null     object
 4   Home_Score   42 non-null     int64
 5   Away_Score   42 non-null     int64
 6   Final_Score  42 non-null     object
dtypes: int64(2), object(5)
memory usage: 2.6+ KB

# Weekly Analysis: Games and Player Performance

## Question 1: All Games and Their Scores

In [61]:
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

# Question 1: All games and their scores
print("=" * 60)
print("ALL GAMES PLAYED THIS WEEK")
print("=" * 60)

# Add point differential column
game_report['Point_Diff'] = abs(game_report['Home_Score'] - game_report['Away_Score'])

# Add date information
if 'GAME_DATE' in games_unique.columns:
    game_report = game_report.merge(
        games_unique[['GAME_ID', 'GAME_DATE']].drop_duplicates(),
        on='GAME_ID',
        how='left'
    )
    game_report = game_report.sort_values('GAME_DATE')

print(f"\nTotal Games: {len(game_report)}")
print("\n" + "=" * 60)
print(game_report[['GAME_DATE', 'Matchup', 'Final_Score', 'Point_Diff']].to_string(index=False))
print("=" * 60)

============================================================
ALL GAMES PLAYED THIS WEEK
============================================================

Total Games: 42

============================================================
 GAME_DATE     Matchup          Final_Score  Point_Diff
2025-10-21   HOU @ OKC HOU @ OKC: 124 - 125           1
2025-10-21   GSW @ LAL GSW @ LAL: 119 - 109          10
2025-10-22 BOS vs. PHI PHI @ BOS: 117 - 116           1
2025-10-22 DAL vs. SAS  SAS @ DAL: 125 - 92          33
2025-10-22   SAC @ PHX SAC @ PHX: 116 - 120           4
2025-10-22   MIN @ POR MIN @ POR: 118 - 114           4
2025-10-22   NOP @ MEM NOP @ MEM: 122 - 128           6
2025-10-22 UTA vs. LAC LAC @ UTA: 108 - 129          21
2025-10-22   WAS @ MIL WAS @ MIL: 120 - 133          13
2025-10-22 NYK vs. CLE CLE @ NYK: 111 - 119           8
2025-10-22   BKN @ CHA BKN @ CHA: 117 - 136          19
2025-10-22   MIA @ ORL MIA @ ORL: 121 - 125           4
2025-10-22 ATL vs. TOR TOR @ ATL: 138 - 118          20
2025-10-22 CHI vs. DET DET @ CHI: 111 - 115           4
2025-10-23 IND vs. OKC OKC @ IND: 141 - 135           6
2025-10-23   DEN @ GSW DEN @ GSW: 131 - 137           6
2025-10-24   ATL @ ORL ATL @ ORL: 111 - 107           4
2025-10-24   MIL @ TOR MIL @ TOR: 122 - 116           6
2025-10-24 SAC vs. UTA UTA @ SAC: 104 - 105           1
2025-10-24 NOP vs. SAS SAS @ NOP: 120 - 116           4
2025-10-24   PHX @ LAC PHX @ LAC: 102 - 129          27
2025-10-24   GSW @ POR GSW @ POR: 119 - 139          20
2025-10-24   CLE @ BKN CLE @ BKN: 131 - 124           7
2025-10-24 DAL vs. WAS WAS @ DAL: 117 - 107          10
2025-10-24   DET @ HOU DET @ HOU: 115 - 111           4
2025-10-24 MEM vs. MIA MIA @ MEM: 146 - 114          32
2025-10-24   BOS @ NYK  BOS @ NYK: 95 - 105          10
2025-10-24   MIN @ LAL MIN @ LAL: 110 - 128          18
2025-10-25   CHA @ PHI CHA @ PHI: 121 - 125           4
2025-10-25   CHI @ ORL  CHI @ ORL: 110 - 98          12
2025-10-25 MEM vs. IND IND @ MEM: 103 - 128          25
2025-10-25   OKC @ ATL OKC @ ATL: 117 - 100          17
2025-10-25   PHX @ DEN PHX @ DEN: 111 - 133          22
2025-10-26 LAC vs. POR POR @ LAC: 107 - 114           7
2025-10-26 SAC vs. LAL LAL @ SAC: 127 - 120           7
2025-10-26 DET vs. BOS BOS @ DET: 113 - 119           6
2025-10-26 WAS vs. CHA CHA @ WAS: 139 - 113          26
2025-10-26   TOR @ DAL TOR @ DAL: 129 - 139          10
2025-10-26   IND @ MIN IND @ MIN: 110 - 114           4
2025-10-26 CLE vs. MIL MIL @ CLE: 113 - 118           5
2025-10-26   NYK @ MIA NYK @ MIA: 107 - 115           8
2025-10-26   BKN @ SAS BKN @ SAS: 107 - 118          11
============================================================

## Question 2: Close Games, Clutch Performances, and Major Comebacks

In [67]:
# Question 2: Close games analysis
print("=" * 60)
print("CLOSE GAMES ANALYSIS")
print("=" * 60)

# Define close game as point differential <= 5
CLOSE_GAME_THRESHOLD = 5
close_games = game_report[game_report['Point_Diff'] <= CLOSE_GAME_THRESHOLD].copy()

if len(close_games) > 0:
    print(f"\nClose Games (Point Differential ≤ {CLOSE_GAME_THRESHOLD}): {len(close_games)}")
    print("\nClose Games Details:")
    print(close_games[['Matchup', 'Final_Score', 'Point_Diff']].to_string(index=False))

============================================================
CLOSE GAMES ANALYSIS
============================================================

Close Games (Point Differential ≤ 5): 13

Close Games Details:
    Matchup          Final_Score  Point_Diff
  HOU @ OKC HOU @ OKC: 124 - 125           1
BOS vs. PHI PHI @ BOS: 117 - 116           1
  SAC @ PHX SAC @ PHX: 116 - 120           4
  MIN @ POR MIN @ POR: 118 - 114           4
  MIA @ ORL MIA @ ORL: 121 - 125           4
CHI vs. DET DET @ CHI: 111 - 115           4
  ATL @ ORL ATL @ ORL: 111 - 107           4
SAC vs. UTA UTA @ SAC: 104 - 105           1
NOP vs. SAS SAS @ NOP: 120 - 116           4
  DET @ HOU DET @ HOU: 115 - 111           4
  CHA @ PHI CHA @ PHI: 121 - 125           4
  IND @ MIN IND @ MIN: 110 - 114           4
CLE vs. MIL MIL @ CLE: 113 - 118           5

In [64]:
# Score progression and comeback analysis
print("\n" + "=" * 60)
print("SCORE PROGRESSION & COMEBACK ANALYSIS")
print("=" * 60)

if 'pbp_df' not in locals() or pbp_df.empty:
    print("\nNo play-by-play data available (pbp_df is empty). Run the PBP fetch cell first.")
else:
    import numpy as np
    import pandas as pd

    # Helper: clean score margin to numeric (home perspective)
    def to_margin_numeric(series):
        s = series.fillna(0).replace({'TIE': 0, '': 0})
        return pd.to_numeric(s, errors='coerce').fillna(0).astype(int)

    # Helper: count lead changes (ignore ties and repeated margins with same sign)
    def count_lead_changes(margins: pd.Series) -> int:
        if margins is None or len(margins) == 0:
            return 0
        m = margins.replace(0, np.nan).dropna().astype(int)
        if m.empty:
            return 0
        # Reduce consecutive same-sign runs
        signs = np.sign(m.values)
        # Count sign transitions
        return int(np.sum(signs[1:] * signs[:-1] == -1))

    # Build mapping GAME_ID -> (Home, Away)
    if 'game_report' in locals() and not game_report.empty:
        id_to_home = dict(zip(game_report['GAME_ID'].astype(str), game_report['Home']))
        id_to_away = dict(zip(game_report['GAME_ID'].astype(str), game_report['Away']))
    else:
        # Fallback using games_unique parsing if needed
        if 'games_unique' in locals() and not games_unique.empty:
            tmp = games_unique[['GAME_ID', 'MATCHUP']].copy()
            is_home_game = tmp['MATCHUP'].str.contains(' vs. ')
            teams = tmp['MATCHUP'].str.split(r' vs. | @ ', regex=True, expand=True)
            tmp['Home'] = np.where(is_home_game, teams[0], teams[1])
            tmp['Away'] = np.where(is_home_game, teams[1], teams[0])
            id_to_home = dict(zip(tmp['GAME_ID'].astype(str), tmp['Home']))
            id_to_away = dict(zip(tmp['GAME_ID'].astype(str), tmp['Away']))
        else:
            id_to_home, id_to_away = {}, {}

    summaries = []

    # Work on either close games or all games this week
    target_games = close_games if 'close_games' in locals() and len(close_games) > 0 else game_report

    for gid in target_games['GAME_ID'].astype(str).unique():
        gpbp = pbp_df[pbp_df['GAME_ID'].astype(str) == gid].copy()
        if gpbp.empty:
            continue

        # Use SCOREMARGIN (home perspective) when available
        if 'SCOREMARGIN' in gpbp.columns:
            margin = to_margin_numeric(gpbp['SCOREMARGIN'])
        elif 'SCORE' in gpbp.columns:
            # Parse SCORE like "85 - 82" (visitor - home in NBA API). Compute margin (home - visitor).
            parts = gpbp['SCORE'].str.split(' - ')
            try:
                visitor = pd.to_numeric(parts.str[0], errors='coerce')
                home = pd.to_numeric(parts.str[1], errors='coerce')
                margin = (home - visitor).fillna(method='ffill').fillna(0).astype(int)
            except Exception:
                margin = pd.Series([0] * len(gpbp), index=gpbp.index)
        else:
            margin = pd.Series([0] * len(gpbp), index=gpbp.index)

        largest_home_lead = int(margin.max())
        largest_away_lead = int((-margin).max())
        lead_changes = count_lead_changes(margin)
        times_tied = int((margin == 0).sum())

        # Determine winner from final margin
        final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
        winner = 'Home' if final_margin > 0 else ('Away' if final_margin < 0 else 'Tie')

        # Biggest comeback size (max deficit for the eventual winner)
        if winner == 'Home':
            biggest_comeback = int(max(0, -margin.min()))
        elif winner == 'Away':
            biggest_comeback = int(max(0, margin.max()))
        else:
            biggest_comeback = 0

        summaries.append({
            'GAME_ID': gid,
            'Home': id_to_home.get(gid, ''),
            'Away': id_to_away.get(gid, ''),
            'Largest_Home_Lead': largest_home_lead,
            'Largest_Away_Lead': largest_away_lead,
            'Lead_Changes': lead_changes,
            'Times_Tied': times_tied,
            'Final_Margin': final_margin,
            'Winner': winner,
            'Biggest_Comeback': biggest_comeback
        })

    if len(summaries) == 0:
        print("No summaries could be generated (missing mappings or PBP).")
    else:
        score_summary = pd.DataFrame(summaries)
        # Add final score if available
        if 'game_report' in locals() and not game_report.empty:
            score_summary = score_summary.merge(
                game_report[['GAME_ID', 'Final_Score']], on='GAME_ID', how='left'
            )

        # Show top comebacks
        print("\nTop Comebacks (by points overcome):")
        print(score_summary.sort_values('Biggest_Comeback', ascending=False)
              .head(10)
              [['GAME_ID', 'Away', 'Home', 'Final_Score', 'Winner', 'Biggest_Comeback']]
              .to_string(index=False))

        # Show most volatile games (lead changes)
        print("\nMost Lead Changes:")
        print(score_summary.sort_values('Lead_Changes', ascending=False)
              .head(10)
              [['GAME_ID', 'Away', 'Home', 'Final_Score', 'Lead_Changes', 'Times_Tied']]
              .to_string(index=False))

        # Save for later use
        score_progression_summary = score_summary
        print("\nSaved score_progression_summary DataFrame for further analysis/plotting.")

============================================================
SCORE PROGRESSION & COMEBACK ANALYSIS
============================================================

Top Comebacks (by points overcome):
   GAME_ID Away Home          Final_Score Winner  Biggest_Comeback
0022500088  SAC  PHX SAC @ PHX: 116 - 120   Home                20
0022500090  ATL  ORL ATL @ ORL: 111 - 107   Away                14
0022500083  PHI  BOS PHI @ BOS: 117 - 116   Away                13
0022500001  HOU  OKC HOU @ OKC: 124 - 125   Home                12
0022500081  MIA  ORL MIA @ ORL: 121 - 125   Home                12
0022500102  CHA  PHI CHA @ PHI: 121 - 125   Home                11
0022500089  MIN  POR MIN @ POR: 118 - 114   Away                 8
0022500095  SAS  NOP SAS @ NOP: 120 - 116   Away                 8
0022500098  UTA  SAC UTA @ SAC: 104 - 105   Home                 6
0022500093  DET  HOU DET @ HOU: 115 - 111   Away                 6

Most Lead Changes:
   GAME_ID Away Home          Final_Score  Lead_Changes  Times_Tied
0022500001  HOU  OKC HOU @ OKC: 124 - 125            22         448
0022500089  MIN  POR MIN @ POR: 118 - 114            17         376
0022500095  SAS  NOP SAS @ NOP: 120 - 116            15         435
0022500093  DET  HOU DET @ HOU: 115 - 111            15         420
0022500110  IND  MIN IND @ MIN: 110 - 114            14         417
0022500083  PHI  BOS PHI @ BOS: 117 - 116            13         373
0022500098  UTA  SAC UTA @ SAC: 104 - 105            11         353
0022500081  MIA  ORL MIA @ ORL: 121 - 125            10         384
0022500102  CHA  PHI CHA @ PHI: 121 - 125             9         382
0022500090  ATL  ORL ATL @ ORL: 111 - 107             7         390

Saved score_progression_summary DataFrame for further analysis/plotting.

/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_30831/3165153463.py:77: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  final_margin = int(margin.replace(0, method='ffill').iloc[-1]) if len(margin) else 0

In [73]:
# Standout players using players DataFrame (season-to-date per-game stats)
print("=" * 60)
print("STANDOUT PLAYERS (players DataFrame)")
print("=" * 60)

if 'players' not in locals() or players is None or players.empty:
    print("\nERROR: players DataFrame not available. Run the leaguedashplayerstats cell first.")
else:
    dfp = players.copy()

    # Normalize player name
    if 'PLAYER_NAME' not in dfp.columns:
        for cand in ['Player_Name', 'PLAYER', 'PLAYER_FULL_NAME']:
            if cand in dfp.columns:
                dfp = dfp.rename(columns={cand: 'PLAYER_NAME'})
                break

    team_col = 'TEAM_ABBREVIATION' if 'TEAM_ABBREVIATION' in dfp.columns else None
    gp_col = 'GP' if 'GP' in dfp.columns else None

    # Stats typically present in leaguedashplayerstats per_mode PerGame
    candidates = ['PTS', 'AST', 'REB', 'STL', 'BLK', 'FG3M']
    available = [c for c in candidates if c in dfp.columns]

    if 'PLAYER_NAME' not in dfp.columns or len(available) == 0:
        print("\nERROR: Missing expected columns in players DataFrame.")
        print(f"Available columns: {list(dfp.columns)[:20]} ...")
    else:
        def show_top(title, metric, n=10):
            if metric not in dfp.columns:
                return
            cols = ['PLAYER_NAME']
            if team_col:
                cols.append(team_col)
            cols.append(metric)
            if gp_col:
                cols.append(gp_col)
            print(f"\n{title}:")
            print(dfp.nlargest(n, metric)[cols].to_string(index=False))

        show_top("Top 10 Scorers (PTS per game)", 'PTS')
        show_top("Top Assist Leaders (AST per game)", 'AST')
        show_top("Top Rebound Leaders (REB per game)", 'REB')
        if 'FG3M' in dfp.columns:
            show_top("Top 3-Point Shooters (3PM per game)", 'FG3M')

        # Simple composite
        if all(c in dfp.columns for c in ['PTS','AST','REB']):
            dfp['BOX_IMPACT'] = dfp['PTS'] + dfp['AST'] + dfp['REB']
            show_top("Overall Box Score Impact (PTS+AST+REB)", 'BOX_IMPACT')

============================================================
STANDOUT PLAYERS (players DataFrame)
============================================================

Top 10 Scorers (PTS per game):
            PLAYER_NAME TEAM_ABBREVIATION  PTS  GP
Shai Gilgeous-Alexander               OKC  174   5
          Austin Reaves               LAL  171   5
           Tyrese Maxey               PHI  150   4
           Devin Booker               PHX  146   5
            Zach LaVine               SAC  146   5
  Giannis Antetokounmpo               MIL  145   4
       Donovan Mitchell               CLE  140   5
        Lauri Markkanen               UTA  136   4
          Stephen Curry               GSW  135   5
           Jaylen Brown               BOS  134   5

Top Assist Leaders (AST per game):
      PLAYER_NAME TEAM_ABBREVIATION  AST  GP
    Austin Reaves               LAL   50   5
     Nikola Jokić               DEN   45   4
  Cade Cunningham               DET   41   5
     Jrue Holiday               POR   39   5
       Trae Young               ATL   39   5
      LaMelo Ball               CHA   38   4
   Keyonte George               UTA   37   4
   Draymond Green               GSW   36   5
Immanuel Quickley               TOR   35   5
  Davion Mitchell               MIA   33   4

Top Rebound Leaders (REB per game):
          PLAYER_NAME TEAM_ABBREVIATION  REB  GP
   Isaiah Hartenstein               OKC   58   5
         Nikola Jokić               DEN   58   4
Giannis Antetokounmpo               MIL   56   4
     Domantas Sabonis               SAC   55   4
    Victor Wembanyama               SAS   55   4
   Karl-Anthony Towns               NYK   54   4
       Nikola Vučević               CHI   53   4
        Anthony Davis               DAL   51   5
          Jalen Duren               DET   50   5
        Deandre Ayton               LAL   47   5

Top 3-Point Shooters (3PM per game):
     PLAYER_NAME TEAM_ABBREVIATION  FG3M  GP
   Stephen Curry               GSW    22   5
      Sam Hauser               BOS    20   5
   Royce O'Neale               PHX    19   5
     Sam Merrill               CLE    18   4
    Tyrese Maxey               PHI    18   4
   Grayson Allen               PHX    17   5
     LaMelo Ball               CHA    17   4
Donovan Mitchell               CLE    16   5
    Kon Knueppel               CHA    16   4
 Lauri Markkanen               UTA    16   4

Overall Box Score Impact (PTS+AST+REB):
            PLAYER_NAME TEAM_ABBREVIATION  BOX_IMPACT  GP
          Austin Reaves               LAL         249   5
Shai Gilgeous-Alexander               OKC         232   5
  Giannis Antetokounmpo               MIL         229   4
           Tyrese Maxey               PHI         198   4
           Devin Booker               PHX         196   5
          Julius Randle               MIN         192   5
      Victor Wembanyama               SAS         190   4
           Nikola Jokić               DEN         184   4
           Jaylen Brown               BOS         181   5
        Cade Cunningham               DET         180   5

In [ ]:
# Export gathered dataframes to CSV files
import os
from datetime import datetime

print("Preparing exports...")

# Collect candidate dataframes if they exist and are not empty
candidates = {}

def add_df(name, df):
    try:
        if df is not None and not df.empty:
            candidates[name] = df.copy()
    except Exception:
        pass

# Core datasets
if 'players' in locals(): add_df('players', players)
if 'teams' in locals(): add_df('teams', teams)
if 'games' in locals(): add_df('games', games)
if 'pbp_df' in locals(): add_df('playbyplay', pbp_df)

# Reports and analyses
if 'game_report' in locals(): add_df('game_report', game_report)
if 'close_games' in locals(): add_df('close_games', close_games)
if 'score_progression_summary' in locals(): add_df('score_progression_summary', score_progression_summary)

# Player-level derived
if 'player_game_stats' in locals(): add_df('player_game_stats', player_game_stats)
if 'player_totals' in locals(): add_df('player_totals', player_totals)
if 'player_performance' in locals(): add_df('player_performance', player_performance)
if 'players_week' in locals(): add_df('players_week', players_week)
if 'rookies_week' in locals(): add_df('rookies_week', rookies_week)
if 'rookie_performance' in locals(): add_df('rookie_performance', rookie_performance)

# Output directory with timestamped subfolder
base_dir = os.path.join('week', 'exports')
ts = datetime.now().strftime('%Y%m%d_%H%M%S')
export_dir = os.path.join(base_dir, ts)
os.makedirs(export_dir, exist_ok=True)

written = []
for name, df in candidates.items():
    path = os.path.join(export_dir, f"{name}.csv")
    try:
        df.to_csv(path, index=False)
        written.append(path)
    except Exception as e:
        print(f"Failed to write {name}: {e}")

if written:
    print("\nExported CSV files:")
    for p in written:
        print(p)
else:
    print("\nNo dataframes found to export.")

In [68]:
# Detailed clutch and comeback analysis using play-by-play
if not pbp_df.empty and len(close_games) > 0:
    print("\n" + "=" * 60)
    print("DETAILED COMEBACK & CLUTCH MOMENTS")
    print("=" * 60)
    
    # Filter pbp for close games only
    close_game_ids_str = close_games['GAME_ID'].astype(str).tolist()
    close_pbp = pbp_df[pbp_df['GAME_ID'].isin(close_game_ids_str)].copy()
    
    # Look for scoring events in 4th quarter (PERIOD == 4) and overtime
    clutch_events = close_pbp[
        (close_pbp['PERIOD'] >= 4) & 
        (close_pbp['EVENTMSGTYPE'].isin([1, 2, 3]))  # Field goals, free throws
    ]
    
    if len(clutch_events) > 0:
        # Get players who scored in clutch time
        clutch_scorers = clutch_events.groupby('PLAYER1_NAME').agg({
            'GAME_ID': 'count'
        }).rename(columns={'GAME_ID': 'Clutch_Events'}).sort_values('Clutch_Events', ascending=False)
        
        print("\nMost Active Players in Clutch Time (4th Quarter + OT):")
        print(clutch_scorers.head(10).to_string())
    else:
        print("\nNo clutch time events found in play-by-play data")
else:
    print("\nSkipping detailed comeback analysis - no play-by-play data or close games available")

============================================================
DETAILED COMEBACK & CLUTCH MOMENTS
============================================================

Most Active Players in Clutch Time (4th Quarter + OT):
                         Clutch_Events
PLAYER1_NAME
Tyrese Maxey                        30
Shai Gilgeous-Alexander             26
Cade Cunningham                     25
Alperen Sengun                      23
Kevin Durant                        17
Paolo Banchero                      17
Zion Williamson                     15
Wendell Carter Jr.                  14
Jaden McDaniels                     13
VJ Edgecombe                        13

## Question 3: Standout Players and Outlier Performances

In [74]:
# Question 3: Standout players and outlier performances
print("=" * 60)
print("STANDOUT PLAYERS & OUTLIER PERFORMANCES")
print("=" * 60)

# Filter player stats for the week's games
# Check if player_game_stats exists (should be created by the player game log fetching cell)
if 'player_game_stats' not in locals() or player_game_stats.empty:
    print("\nERROR: Player game stats not available.")
    print("Please run the 'Fetch Player Game Logs for This Week' cell first.")
    player_totals = pd.DataFrame()
else:
    # Use player_game_stats directly (already filtered for this week's games)
    game_id_col = 'Game_ID' if 'Game_ID' in player_game_stats.columns else 'GAME_ID'
    team_col = 'TEAM_ABBREVIATION' if 'TEAM_ABBREVIATION' in player_game_stats.columns else None
    
    if 'PLAYER_NAME' not in player_game_stats.columns:
        print(f"\nERROR: PLAYER_NAME column not found.")
        print(f"Available columns: {list(player_game_stats.columns)}")
        player_totals = pd.DataFrame()
    else:
        groupby_cols = ['PLAYER_NAME']
        if team_col:
            groupby_cols.append(team_col)
        
        # Build agg_dict with only columns that exist
        agg_dict = {}
        stat_cols = ['PTS', 'AST', 'REB', 'STL', 'BLK', 'FG3M', 'MIN']
        for col in stat_cols:
            if col in player_game_stats.columns:
                agg_dict[col] = 'sum'
        
        if game_id_col in player_game_stats.columns:
            agg_dict[game_id_col] = 'count'
        
        if len(agg_dict) > 0:
            player_totals = player_game_stats.groupby(groupby_cols).agg(agg_dict).rename(columns={game_id_col: 'Games_Played'}).reset_index()
            
            # Calculate per game averages (only if we have games played)
            if 'Games_Played' in player_totals.columns:
                if 'PTS' in player_totals.columns:
                    player_totals['PPG'] = player_totals['PTS'] / player_totals['Games_Played']
                if 'AST' in player_totals.columns:
                    player_totals['APG'] = player_totals['AST'] / player_totals['Games_Played']
                if 'REB' in player_totals.columns:
                    player_totals['RPG'] = player_totals['REB'] / player_totals['Games_Played']
                
                # Display results
                if 'PTS' in player_totals.columns and 'PPG' in player_totals.columns:
                    print("\nTop 10 Scorers (Total Points):")
                    display_cols = ['PLAYER_NAME']
                    if team_col:
                        display_cols.append(team_col)
                    display_cols.extend(['PTS', 'PPG', 'Games_Played'])
                    print(player_totals.nlargest(10, 'PTS')[display_cols].to_string(index=False))
                    
                    print("\nTop 10 Scorers (Per Game Average):")
                    display_cols = ['PLAYER_NAME']
                    if team_col:
                        display_cols.append(team_col)
                    display_cols.extend(['PPG', 'PTS', 'Games_Played'])
                    print(player_totals.nlargest(10, 'PPG')[display_cols].to_string(index=False))
                
                if 'AST' in player_totals.columns and 'APG' in player_totals.columns:
                    print("\nTop Assist Leaders:")
                    display_cols = ['PLAYER_NAME']
                    if team_col:
                        display_cols.append(team_col)
                    display_cols.extend(['AST', 'APG', 'Games_Played'])
                    print(player_totals.nlargest(10, 'AST')[display_cols].to_string(index=False))
                
                if 'REB' in player_totals.columns and 'RPG' in player_totals.columns:
                    print("\nTop Rebound Leaders:")
                    display_cols = ['PLAYER_NAME']
                    if team_col:
                        display_cols.append(team_col)
                    display_cols.extend(['REB', 'RPG', 'Games_Played'])
                    print(player_totals.nlargest(10, 'REB')[display_cols].to_string(index=False))
                
                if 'FG3M' in player_totals.columns:
                    print("\nTop 3-Point Shooters:")
                    display_cols = ['PLAYER_NAME']
                    if team_col:
                        display_cols.append(team_col)
                    display_cols.extend(['FG3M', 'Games_Played'])
                    print(player_totals.nlargest(10, 'FG3M')[display_cols].to_string(index=False))
            else:
                print("\nNo valid columns found for aggregation")
                player_totals = pd.DataFrame()
        else:
            print("\nNo valid stat columns found in player_game_stats")
            player_totals = pd.DataFrame()

============================================================
STANDOUT PLAYERS & OUTLIER PERFORMANCES
============================================================

ERROR: PLAYER_NAME column not found.
Available columns: ['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE']

In [72]:
# Identify outlier performances (single-game high performances)
print("\n" + "=" * 60)
print("OUTLIER SINGLE-GAME PERFORMANCES")
print("=" * 60)

# Check if player_game_stats exists and has required columns
if 'player_game_stats' not in locals() or player_game_stats.empty:
    print("\nERROR: Player game stats not available.")
    print("Please run the 'Fetch Player Game Logs for This Week' cell first.")
elif 'PLAYER_NAME' not in player_game_stats.columns:
    print("\nERROR: PLAYER_NAME column not found.")
    print(f"Available columns: {list(player_game_stats.columns)}")
else:
    # Single game performances
    single_game_stats = player_game_stats.copy()
    
    # Check which stat columns exist
    has_pts = 'PTS' in single_game_stats.columns
    has_ast = 'AST' in single_game_stats.columns
    has_reb = 'REB' in single_game_stats.columns
    has_team = 'TEAM_ABBREVIATION' in single_game_stats.columns
    has_matchup = 'MATCHUP' in single_game_stats.columns
    
    # Build display columns list dynamically
    def get_display_cols(required_cols):
        display = []
        for col in required_cols:
            if col == 'PLAYER_NAME' and 'PLAYER_NAME' in single_game_stats.columns:
                display.append('PLAYER_NAME')
            elif col == 'TEAM_ABBREVIATION' and has_team:
                display.append('TEAM_ABBREVIATION')
            elif col == 'PTS' and has_pts:
                display.append('PTS')
            elif col == 'AST' and has_ast:
                display.append('AST')
            elif col == 'REB' and has_reb:
                display.append('REB')
            elif col == 'MATCHUP' and has_matchup:
                display.append('MATCHUP')
        return display
    
    if has_pts:
        print("\nHighest Single Game Scores:")
        display_cols = get_display_cols(['PLAYER_NAME', 'TEAM_ABBREVIATION', 'PTS', 'AST', 'REB', 'MATCHUP'])
        if len(display_cols) > 0:
            print(single_game_stats.nlargest(10, 'PTS')[display_cols].to_string(index=False))
        else:
            print("No displayable columns available")
    
    if has_ast:
        print("\nHighest Single Game Assists:")
        display_cols = get_display_cols(['PLAYER_NAME', 'TEAM_ABBREVIATION', 'AST', 'PTS', 'REB', 'MATCHUP'])
        if len(display_cols) > 0:
            print(single_game_stats.nlargest(10, 'AST')[display_cols].to_string(index=False))
    
    if has_reb:
        print("\nHighest Single Game Rebounds:")
        display_cols = get_display_cols(['PLAYER_NAME', 'TEAM_ABBREVIATION', 'REB', 'PTS', 'AST', 'MATCHUP'])
        if len(display_cols) > 0:
            print(single_game_stats.nlargest(10, 'REB')[display_cols].to_string(index=False))
    
    # Triple-doubles and special performances
    if has_pts and has_ast and has_reb:
        triple_doubles = single_game_stats[
            (single_game_stats['PTS'] >= 10) & 
            (single_game_stats['AST'] >= 10) & 
            (single_game_stats['REB'] >= 10)
        ].copy()
        
        if len(triple_doubles) > 0:
            print("\n" + "=" * 60)
            print("TRIPLE-DOUBLES THIS WEEK")
            print("=" * 60)
            display_cols = get_display_cols(['PLAYER_NAME', 'TEAM_ABBREVIATION', 'PTS', 'AST', 'REB', 'MATCHUP'])
            if len(display_cols) > 0:
                print(triple_doubles[display_cols].to_string(index=False))
        else:
            print("\nNo triple-doubles this week")
    
    # 40+ point games
    if has_pts:
        high_scoring = single_game_stats[single_game_stats['PTS'] >= 40].copy()
        if len(high_scoring) > 0:
            print("\n" + "=" * 60)
            print("40+ POINT GAMES")
            print("=" * 60)
            display_cols = get_display_cols(['PLAYER_NAME', 'TEAM_ABBREVIATION', 'PTS', 'MATCHUP'])
            if len(display_cols) > 0:
                print(high_scoring[display_cols].to_string(index=False))
        else:
            print("\nNo 40+ point games this week")

============================================================
OUTLIER SINGLE-GAME PERFORMANCES
============================================================

ERROR: PLAYER_NAME column not found.
Available columns: ['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE']