In [1]:
from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd

Game data from past 7 days (10/20 - 10/26)

In [2]:
data = leaguedashplayerstats.LeagueDashPlayerStats(season='2025-26')
players = data.get_data_frames()[0]
players.info
players.columns #player data

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK',
       'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK',
       'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK',
       'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK',
       'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK',
       'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT'],
      dtype='object')

In [3]:
from nba_api.stats.endpoints import leaguedashteamstats
DATE_FROM = "2025-10-01"   
DATE_TO   = "2025-10-27"   

resp = leaguedashteamstats.LeagueDashTeamStats(
    season='2025-26',
    season_type_all_star='Regular Season',   # or 'Pre Season' if you want preseason
    date_from_nullable=DATE_FROM,
    date_to_nullable=DATE_TO,
    per_mode_detailed='PerGame'              # 'Totals' if you want raw sums
)

teams = resp.get_data_frames()[0]
teams # team data

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,4,1,3,0.250,48.0,40.8,89.5,0.455,...,28,10,4,22,17,5,4,15,25,24
1,1610612738,Boston Celtics,4,1,3,0.250,48.0,40.5,90.5,0.448,...,17,30,2,17,3,2,25,28,26,14
2,1610612751,Brooklyn Nets,4,0,4,0.000,48.0,40.8,89.3,0.457,...,29,17,14,25,30,18,28,23,21,30
3,1610612766,Charlotte Hornets,3,2,1,0.667,48.0,46.0,90.3,0.509,...,8,1,13,24,18,10,9,2,1,2
4,1610612741,Chicago Bulls,3,3,0,1.000,48.0,42.0,87.3,0.481,...,8,5,29,20,15,25,14,16,16,8
5,1610612739,Cleveland Cavaliers,4,3,1,0.750,48.0,40.5,85.0,0.476,...,25,15,20,3,19,5,12,4,14,9
6,1610612742,Dallas Mavericks,4,1,3,0.250,48.0,38.0,85.8,0.443,...,18,22,16,14,13,17,3,10,30,26
7,1610612743,Denver Nuggets,3,2,1,0.667,49.7,46.7,89.0,0.524,...,14,6,7,11,27,25,14,21,2,4
8,1610612765,Detroit Pistons,4,2,2,0.500,48.0,39.3,91.8,0.428,...,7,21,23,17,1,27,29,11,28,21
9,1610612744,Golden State Warriors,4,3,1,0.750,49.3,41.8,85.0,0.491,...,24,3,20,6,19,5,8,17,4,16
10,1610612745,Houston Rockets,3,1,2,0.333,51.3,41.3,88.3,0.468,...,12,23,15,6,21,18,20,1,6,7
11,1610612754,Indiana Pacers,3,0,3,0.000,51.3,40.3,95.0,0.425,...,6,24,8,30,15,3,30,5,20,27
12,1610612746,LA Clippers,3,2,1,0.667,48.0,42.7,81.3,0.525,...,16,7,30,4,5,10,9,21,17,13
13,1610612747,Los Angeles Lakers,4,2,2,0.500,48.0,41.5,79.8,0.520,...,22,19,28,17,25,18,1,13,15,17
14,1610612763,Memphis Grizzlies,4,2,2,0.500,48.0,40.8,90.0,0.453,...,20,9,5,27,8,13,11,9,9,19
15,1610612748,Miami Heat,3,2,1,0.667,48.0,45.7,92.0,0.496,...,2,8,27,4,27,15,14,26,3,3
16,1610612749,Milwaukee Bucks,3,2,1,0.667,48.0,45.7,89.0,0.513,...,13,10,10,10,10,3,20,26,8,12
17,1610612750,Minnesota Timberwolves,4,2,2,0.500,48.0,40.5,85.8,0.472,...,22,27,10,22,3,9,23,23,22,22
18,1610612740,New Orleans Pelicans,3,0,3,0.000,49.7,38.3,93.0,0.412,...,19,29,8,11,29,30,18,2,29,29
19,1610612752,New York Knicks,3,2,1,0.667,48.0,36.0,90.0,0.400,...,3,25,18,20,21,10,5,23,27,15
20,1610612760,Oklahoma City Thunder,4,4,0,1.000,53.0,43.5,95.5,0.455,...,4,26,3,11,24,13,23,8,11,6
21,1610612753,Orlando Magic,4,1,3,0.250,48.0,39.5,84.3,0.469,...,11,27,23,27,11,18,17,6,24,23
22,1610612755,Philadelphia 76ers,3,3,0,1.000,48.0,42.7,89.7,0.476,...,26,14,1,29,6,15,22,7,5,11
23,1610612756,Phoenix Suns,4,1,3,0.250,49.3,41.3,94.8,0.435,...,15,12,19,8,8,18,27,17,18,28
24,1610612757,Portland Trail Blazers,4,2,2,0.500,48.0,41.8,94.5,0.442,...,20,13,23,1,13,29,2,13,13,10
25,1610612758,Sacramento Kings,3,1,2,0.333,48.0,44.0,92.7,0.475,...,30,18,5,2,6,8,7,29,23,18
26,1610612759,San Antonio Spurs,4,4,0,1.000,49.3,43.3,82.5,0.524,...,5,19,23,14,2,1,12,11,11,1
27,1610612761,Toronto Raptors,4,1,3,0.250,48.0,45.5,89.8,0.507,...,27,2,16,8,25,24,25,17,10,19
28,1610612762,Utah Jazz,3,2,1,0.667,49.7,43.3,93.7,0.463,...,1,4,22,16,21,28,5,20,7,5
29,1610612764,Washington Wizards,3,1,2,0.333,48.0,42.7,93.0,0.459,...,10,16,10,26,12,18,18,30,19,25

In [4]:
from nba_api.stats.endpoints import leaguegamelog

gamelog = leaguegamelog.LeagueGameLog(
    season='2025-26',
    season_type_all_star='Regular Season'
)
#game data
games = gamelog.get_data_frames()[0]

In [5]:
games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'] )

In [6]:
games = games[(games['GAME_DATE'] >= '2025-10-20') & (games['GAME_DATE'] <= '2025-10-26')]
games['GAME_DATE']

0    2025-10-21
1    2025-10-21
2    2025-10-21
3    2025-10-21
4    2025-10-22
        ...
79   2025-10-26
80   2025-10-26
81   2025-10-26
82   2025-10-26
83   2025-10-26
Name: GAME_DATE, Length: 84, dtype: datetime64[ns]

In [7]:
#get data of how the game progressed over time...quarter by quarter stats?
from nba_api.stats.endpoints import playbyplayv2
from time import sleep

game_ids = games["GAME_ID"].astype(str).unique()
all_pbp = []
for gid in game_ids:
    try:
        pbp = playbyplayv2.PlayByPlayV2(game_id=gid)
        df = pbp.get_data_frames()[0]
        df["GAME_ID"] = gid  # keep game id for reference
        all_pbp.append(df)
        sleep(0.6)  
    except Exception as e:
        print(f"Failed {gid}: {e}")

pbp_df = pd.concat(all_pbp, ignore_index=True) if all_pbp else pd.DataFrame()
pbp_df

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0022500001,2,12,0,1,7:44 PM,12:00,None,Start of 1st Period (7:44 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1
1,0022500001,4,10,0,1,7:44 PM,12:00,Jump Ball Holmgren vs. Adams: Tip to Thompson,None,None,...,Rockets,HOU,5,1641708,Amen Thompson,1.610613e+09,Houston,Rockets,HOU,1
2,0022500001,8,2,1,1,7:44 PM,11:36,None,None,MISS Sengun 25' 3PT Jump Shot,...,None,None,0,0,None,NaN,None,None,None,1
3,0022500001,9,4,0,1,7:44 PM,11:31,Wallace REBOUND (Off:0 Def:1),None,None,...,None,None,0,0,None,NaN,None,None,None,1
4,0022500001,10,1,98,1,7:45 PM,11:26,Holmgren 1' Cutting Layup Shot (2 PTS) (Dort 1...,None,None,...,Thunder,OKC,0,0,None,NaN,None,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21442,0022500105,702,4,0,4,4:44 PM,0:27,SPURS Rebound,None,None,...,None,None,0,0,None,NaN,None,None,None,1
21443,0022500105,704,5,11,4,4:44 PM,0:03,SPURS Turnover: Shot Clock (T#15),None,None,...,None,None,1,0,None,NaN,None,None,None,1
21444,0022500105,705,6,11,4,4:44 PM,0:03,None,Jordi Fernandez Foul:T.FOUL (T.Ford),None,...,None,None,1,0,None,NaN,None,None,None,1
21445,0022500105,706,3,16,4,4:45 PM,0:03,Wembanyama Free Throw Technical (31 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,1
21446,0022500105,707,13,0,4,4:45 PM,0:00,None,End of 4th Period (4:45 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1

 all the above data can go into a postgres database, its pretty much the whole base info for the week

In [8]:
games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,290,43,...,36,52,23,6,5,25,26,124,-1,1
1,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,240,38,...,31,40,29,10,4,19,27,119,10,1
2,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,240,42,...,32,39,23,7,2,20,21,109,-10,1
3,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,290,46,...,27,38,29,12,4,12,27,125,1,1
4,22025,1610612737,ATL,Atlanta Hawks,0022500082,2025-10-22,ATL vs. TOR,L,240,38,...,26,34,25,7,6,16,24,118,-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,22025,1610612749,MIL,Milwaukee Bucks,0022500107,2025-10-26,MIL @ CLE,L,240,40,...,28,37,25,12,6,18,26,113,-5,1
80,22025,1610612764,WAS,Washington Wizards,0022500109,2025-10-26,WAS vs. CHA,L,240,41,...,33,40,25,5,4,15,27,113,-26,1
81,22025,1610612751,BKN,Brooklyn Nets,0022500105,2025-10-26,BKN @ SAS,L,240,34,...,23,34,22,9,0,12,30,107,-11,1
82,22025,1610612759,SAS,San Antonio Spurs,0022500105,2025-10-26,SAS vs. BKN,W,240,39,...,34,45,20,7,6,15,23,118,11,1
83,22025,1610612766,CHA,Charlotte Hornets,0022500109,2025-10-26,CHA @ WAS,W,240,47,...,41,52,30,12,4,12,16,139,26,1

In [20]:
#all the games and their scores displayed neatly

#parse through the game data, given each game id
#show the home team, the away team, and the final score 

    #parse the 'matchup'  ..home team -> @ , away team -> vs 

games_unique = games.drop_duplicates(subset=['GAME_ID'])
games_unique
game_report = pd.DataFrame()

In [19]:
import numpy as np

# Create game_report from games_unique
game_report = games_unique[['GAME_ID', 'MATCHUP']].copy()

# Parse home and away teams from MATCHUP
# Format: "LAL vs. BOS" = LAL is home, "LAL @ BOS" = BOS is home
is_home_game = game_report['MATCHUP'].str.contains(' vs. ')
teams = game_report['MATCHUP'].str.split(r' vs. | @ ', regex=True, expand=True)

game_report['Home'] = np.where(is_home_game, teams[0], teams[1])
game_report['Away'] = np.where(is_home_game, teams[1], teams[0])
game_report['Matchup'] = game_report['MATCHUP']

# Get final scores by grouping games DataFrame (has both teams' scores)
scores = games.groupby('GAME_ID').agg({
    'TEAM_ABBREVIATION': list,
    'PTS': list
}).reset_index()

# Merge scores with game_report to get final scores
def get_scores(row):
    game_id = row['GAME_ID']
    score_data = scores[scores['GAME_ID'] == game_id]
    if len(score_data) == 0:
        return np.nan, np.nan
    
    teams_list = score_data.iloc[0]['TEAM_ABBREVIATION']
    pts_list = score_data.iloc[0]['PTS']
    
    # Find which score belongs to home and which to away
    home_idx = teams_list.index(row['Home']) if row['Home'] in teams_list else None
    away_idx = teams_list.index(row['Away']) if row['Away'] in teams_list else None
    
    if home_idx is not None and away_idx is not None:
        return pts_list[home_idx], pts_list[away_idx]
    return np.nan, np.nan

game_report[['Home_Score', 'Away_Score']] = game_report.apply(
    lambda row: pd.Series(get_scores(row)), axis=1
)


game_report['Final_Score'] = game_report.apply(
    lambda row: f"{row['Away']} @ {row['Home']}: {int(row['Away_Score'])} - {int(row['Home_Score'])}",
    axis=1
)

# Select and reorder columns
game_report = game_report[['GAME_ID', 'Matchup', 'Home', 'Away', 'Home_Score', 'Away_Score', 'Final_Score']]

# Ensure unique games only (drop duplicates by GAME_ID)
game_report = game_report.drop_duplicates(subset=['GAME_ID'], keep='first')
game_report

,GAME_ID,Matchup,Home,Away,Home_Score,Away_Score,Final_Score
0,0022500001,HOU @ OKC,OKC,HOU,125,124,HOU @ OKC: 124 - 125
1,0022500002,GSW @ LAL,LAL,GSW,109,119,GSW @ LAL: 119 - 109
4,0022500082,ATL vs. TOR,ATL,TOR,118,138,TOR @ ATL: 138 - 118
5,0022500081,MIA @ ORL,ORL,MIA,125,121,MIA @ ORL: 121 - 125
6,0022500080,BKN @ CHA,CHA,BKN,136,117,BKN @ CHA: 117 - 136
7,0022500003,NYK vs. CLE,NYK,CLE,119,111,CLE @ NYK: 111 - 119
9,0022500086,WAS @ MIL,MIL,WAS,133,120,WAS @ MIL: 120 - 133
11,0022500084,CHI vs. DET,CHI,DET,115,111,DET @ CHI: 111 - 115
14,0022500085,NOP @ MEM,MEM,NOP,128,122,NOP @ MEM: 122 - 128
18,0022500089,MIN @ POR,POR,MIN,114,118,MIN @ POR: 118 - 114
19,0022500087,UTA vs. LAC,UTA,LAC,129,108,LAC @ UTA: 108 - 129
22,0022500088,SAC @ PHX,PHX,SAC,120,116,SAC @ PHX: 116 - 120
23,0022500004,DAL vs. SAS,DAL,SAS,92,125,SAS @ DAL: 125 - 92
26,0022500083,BOS vs. PHI,BOS,PHI,116,117,PHI @ BOS: 117 - 116
28,0022500005,IND vs. OKC,IND,OKC,135,141,OKC @ IND: 141 - 135
30,0022500006,DEN @ GSW,GSW,DEN,137,131,DEN @ GSW: 131 - 137
32,0022500018,BOS @ NYK,NYK,BOS,105,95,BOS @ NYK: 95 - 105
33,0022500094,MEM vs. MIA,MEM,MIA,114,146,MIA @ MEM: 146 - 114
34,0022500093,DET @ HOU,HOU,DET,111,115,DET @ HOU: 115 - 111
35,0022500096,DAL vs. WAS,DAL,WAS,107,117,WAS @ DAL: 117 - 107
36,0022500091,CLE @ BKN,BKN,CLE,124,131,CLE @ BKN: 131 - 124
38,0022500019,MIN @ LAL,LAL,MIN,128,110,MIN @ LAL: 110 - 128
39,0022500097,GSW @ POR,POR,GSW,139,119,GSW @ POR: 119 - 139
41,0022500090,ATL @ ORL,ORL,ATL,107,111,ATL @ ORL: 111 - 107
45,0022500099,PHX @ LAC,LAC,PHX,129,102,PHX @ LAC: 102 - 129
46,0022500095,NOP vs. SAS,NOP,SAS,116,120,SAS @ NOP: 120 - 116
49,0022500098,SAC vs. UTA,SAC,UTA,105,104,UTA @ SAC: 104 - 105
51,0022500092,MIL @ TOR,TOR,MIL,116,122,MIL @ TOR: 122 - 116
56,0022500100,CHI @ ORL,ORL,CHI,98,110,CHI @ ORL: 110 - 98
57,0022500103,MEM vs. IND,MEM,IND,128,103,IND @ MEM: 103 - 128
60,0022500101,OKC @ ATL,ATL,OKC,100,117,OKC @ ATL: 117 - 100
61,0022500104,PHX @ DEN,DEN,PHX,133,111,PHX @ DEN: 111 - 133
64,0022500102,CHA @ PHI,PHI,CHA,125,121,CHA @ PHI: 121 - 125
66,0022500107,CLE vs. MIL,CLE,MIL,118,113,MIL @ CLE: 113 - 118
67,0022500110,IND @ MIN,MIN,IND,114,110,IND @ MIN: 110 - 114
68,0022500111,TOR @ DAL,DAL,TOR,139,129,TOR @ DAL: 129 - 139
69,0022500108,NYK @ MIA,MIA,NYK,115,107,NYK @ MIA: 107 - 115
72,0022500106,DET vs. BOS,DET,BOS,119,113,BOS @ DET: 113 - 119
74,0022500113,SAC vs. LAL,SAC,LAL,120,127,LAL @ SAC: 127 - 120
76,0022500112,LAC vs. POR,LAC,POR,114,107,POR @ LAC: 107 - 114
80,0022500109,WAS vs. CHA,WAS,CHA,113,139,CHA @ WAS: 139 - 113
81,0022500105,BKN @ SAS,SAS,BKN,118,107,BKN @ SAS: 107 - 118